@startuml

package izzum.statemachine {
    Class StateMachine {
      # states: State[]
      # transitions: Transition[]
      # context: Context
      + canTransition(transition:string):boolean
      + transition(transition:string)
      + handle(event:string):boolean
      + run():boolean
      + runToCompletion():int
      + getTransitions():Transition[]
      + getStates(): State[]
      + addTransition(Transition)
      + changeContext(Context)
      + getContext():Context
      + getCurrentState():State
      + getInitialState(): State
      - checkCanTransition(Transition):boolean
      - callCallable($object, method, args)
      # setState(State)
      # _checkCanTransition(Transition, event)
      # _preProcess(Transition, event)
      # _onExitState(Transition, event)
      # _onTransition(Transition, event)
      # _onEnterState(Transtion, event)
      # _postProcess(Transition, event)
      # handleTransitionException(Transition, Exception)   
    }
    
    Class State {
        # name: string
        # type:string
        # transitions: Transition[]
        # description:string
        + getName():string
        + getType():string
        + getTransitions():Transition[]
        + hasTransition(name:string):boolean
        + exitAction(Context)
        + entryAction(Context)
        + getTransitionTriggeredByEvent(event:string)
    }
    Class Transition {
        # state_from:State
        # state_to:State
        # rule:string
        # command:string
        # description: string
        # event: string
        + can(Context, event:string)
        + process(Context, event:string)
        + getRule(Context, event:string):Rule
        + getCommand(Context, event:string): Command
        + getRuleName():string
        + getCommandName():string
        + isTriggeredBy(event:string)
    }
    Class Context {
        # identifier:Identifier
        # entity_builder: EntityBuilder
        # persistence_adapter: Adapter
        # statemachine:StateMachine
        + getEntity():*
        + getEntityId():string
        + getMachine():string
        + getStateMachine():StateMachine
        + getState():string
        + setState(state)
        + getBuilder():EntityBuilder
        + getPersistenceAdapter():Adapter
        + setStateMachine(StateMachine)
        + setFailedTransition(Transition, Exception)
    }
    
    Class Identifier {
    	# entity_id:string
    	# machine_name:string
    	+ getEntityId():string
    	+ getMachine():string
    	+ getId():string
    }

    Class EntityBuilder {
        + getEntity(Identifier):*
        # build():*
    }
    package persistence {
      abstract Class Adapter {
        + {abstract} getEntityIds(machine:string, state:string):string[]
        + {abstract} add(Identifier):boolean
        + getInitialState(Identifier):string
        + setState(Identifier):boolean
        + getState(Identifier)
        + setFailedTransition(Exception, transition:string)
        # {abstract} processSetState(Identifier):boolean
        # {abstract} processGetState(Identifier)
      }

      Class PDO {
        #dsn:string
        + load(StateMachine)
      }

      Class Memory {

      }

      Class Session {

      }

    }

        abstract Class AbstractFactory {
            + getStateMachine(id):StateMachine
            # {abstract} createLoader(): Loader
            # {abstract} createAdapter(): Adapter
            # {abstract} createBuilder(): EntityBuilder
            # {abstract} getMachineName(): string
            # createMachine(Context): StateMachine
            # createContext(Identifier): Context
            +add(Context)
        }

    package loader {
        Interface Loader {
          +load(StateMachine)
        }
        Class LoaderArray {
          # transitions: Transition[]
          + load(StateMachine)
          + add(Transition)
        }
    }

    Class Exception

    package command {
      Class Command {
        +execute()
        #{abstract}_execute()
      }
    }

    package rules {
      Class Rule {
        +applies():boolean
        #{abstract}_applies():boolean
      }
    }

}
    StateMachine "1" o-- "n" State : uses
    StateMachine "1" o-- "n" Transition : does
    StateMachine "1" o-- "1" Context : needs and uses
    StateMachine "1" --> "n" Exception: throws
    Context "n" o-- "1" EntityBuilder : gets domain object (alias: DO)
    Context "n" o-- "1" Adapter : read/write state info
    Context "1" o-- "1" Identifier : use to ID the DO/entity
    State "n" -- "n" Transition : need each other
    Adapter <|-- Memory
    Adapter <|-- PDO : database interfacing
    Adapter <|-- Session
    Loader <|.. PDO : storage and loading
    Loader <|.. LoaderArray 
    Transition *-- Command : logic to process transitions (DO)
    Transition *-- Rule : check if transition allowed (DO)
    Transition "n" --> "1" Context : acts on
    AbstractFactory "1" --> "n" StateMachine: creates SM, Adapter, Loader, Context, Identifier, EntityBuilder
    Loader "1" --> "n" StateMachine : adds transitions



@enduml

